name: Build UF2 on push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: thinkier/pico-build@69db1876bfe02de9bbe008492ad51bf312ba8d85
